// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllDoctors() {
  return window['go']['backend']['DoctorService']['GetAllDoctors']();
}
