// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportPatientsFromExcel(arg1:string):Promise<void>;

export function ImportPatientsFromExcelBase64(arg1:string,arg2:string):Promise<void>;
