// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportPatientsFromExcel(arg1) {
  return window['go']['backend']['ExcelService']['ImportPatientsFromExcel'](arg1);
}

export function ImportPatientsFromExcelBase64(arg1, arg2) {
  return window['go']['backend']['ExcelService']['ImportPatientsFromExcelBase64'](arg1, arg2);
}
