// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {backend} from '../models';

export function CreatePatient(arg1:models.CreateInput):Promise<models.Patient>;

export function DeletePatient(arg1:string):Promise<void>;

export function GetAllPatients(arg1:backend.PaginationParams):Promise<backend.PaginatedPatients>;

export function GetPatientByCode(arg1:string):Promise<models.Patient>;

export function GetTotalPatient():Promise<backend.PatientTotal>;

export function UpdatePatient(arg1:string,arg2:models.CreateInput):Promise<models.Patient>;
