// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePatient(arg1) {
  return window['go']['backend']['PatientService']['CreatePatient'](arg1);
}

export function DeletePatient(arg1) {
  return window['go']['backend']['PatientService']['DeletePatient'](arg1);
}

export function GetAllPatients(arg1) {
  return window['go']['backend']['PatientService']['GetAllPatients'](arg1);
}

export function GetPatientByCode(arg1) {
  return window['go']['backend']['PatientService']['GetPatientByCode'](arg1);
}

export function GetTotalPatient() {
  return window['go']['backend']['PatientService']['GetTotalPatient']();
}

export function UpdatePatient(arg1, arg2) {
  return window['go']['backend']['PatientService']['UpdatePatient'](arg1, arg2);
}
