// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {backend} from '../models';

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.User>;

export function DeleteUser(arg1:number):Promise<void>;

export function GetUserById(arg1:number):Promise<models.User>;

export function GetUsers():Promise<Array<models.User>>;

export function Login(arg1:string,arg2:string):Promise<backend.LoginResponse>;

export function Logout(arg1:string):Promise<backend.LoginResponse>;

export function UpdateUser(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<models.User>;
