// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['UserService']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function DeleteUser(arg1) {
  return window['go']['backend']['UserService']['DeleteUser'](arg1);
}

export function GetUserById(arg1) {
  return window['go']['backend']['UserService']['GetUserById'](arg1);
}

export function GetUsers() {
  return window['go']['backend']['UserService']['GetUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['backend']['UserService']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['backend']['UserService']['Logout'](arg1);
}

export function UpdateUser(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['backend']['UserService']['UpdateUser'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
