// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateVisit(arg1:number,arg2:number,arg3:string,arg4:string):Promise<models.Visit>;

export function ExpireOldVisits():Promise<void>;

export function GetAllVisitsToday(arg1:string):Promise<Array<models.Visit>>;

export function UpdatePatientStatus():Promise<void>;

export function UpdateQueueNumber(arg1:number,arg2:number):Promise<void>;

export function UpdateVisitStatus(arg1:number,arg2:string):Promise<void>;
